#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

# Add it here based on
# https://github.com/Askannz/optimus-manager/issues/205#issuecomment-627364593
# https://bbs.archlinux.org/viewtopic.php?id=255752  (Post #8)
prime-offload &

# Display resolution
xrandr --output DP-0 --auto --output DP-1 --auto --right-of DP-0 --auto --output LVDS-1-1 --primary --left-of DP-0 --auto
# xrandr --output VGA-1-1 --auto --output DP-1 --auto --right-of VGA-1-1 --auto --output LVDS-1-1 --primary --left-of VGA-1-1 --auto

# xrandr --output DP-0 --auto --output DP-1 --auto --right-of DP-0 &
# xrandr --output LVDS-1-2 --auto --left-of DP-0 &
# xrandr --output LVDS-1-2 --auto  &

#xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources & xrdbpid=$!	# Uncomment to use Xresources colors/settings on startup
#xrdb -load ${XDG_CONFIG_HOME:-$HOME/.config}/x11/Xresources &		# Uncomment to use Xresources colors/settings on startup

# xrandr --dpi 96		# Set DPI. User may want to use a larger number for larger screens.
setbg &           # Set the background with the `setbg` script

# NOTE: Luke Smith runs his dwmblocks within his dwm build:
# https://github.com/LukeSmithxyz/dwm/commit/02bda162f7e8561462bb4765a36214a2249a7761
autostart="mpd picom dunst lxsession unclutter redshift clipmenud remapd"

for program in $autostart; do
	pidof -sx "$program" || "$program" &
done >/dev/null 2>&1

# Ensure that xrdb has finished running before moving on to start the WM/DE.
[ -n "$xrdbpid" ] && wait "$xrdbpid"
