#!/usr/bin/env bash
if [[ -z $STOW_FOLDERS ]]; then
    STOW_FOLDERS="x11,shell,nvim"
fi

if [[ -z $DOTFILES ]]; then
    DOTFILES=$HOME/.dotfiles
fi

export STOW_FOLDERS=$STOW_FOLDERS 
export DOTFILES=$DOTFILES 

$DOTFILES/install
