gui:
  theme: # https://github.com/catppuccin/lazygit/blob/main/themes/frappe/blue.yml
    lightTheme: false
    activeBorderColor:
      - '#8caaee'
      - bold
    inactiveBorderColor:
      - '#a5adce'
    optionsTextColor:
      - '#8caaee'
    selectedLineBgColor:
      - '#8caaee'
    cherryPickedCommitBgColor:
      - '#51576d'
    cherryPickedCommitFgColor:
      - '#8caaee'
    unstagedChangesColor:
      - '#e78284'
    defaultFgColor:
      - '#c6d0f5'
    searchingActiveBorderColor:
      - '#e5c890'

  authorColors:
    '*': '#babbf1'

  showFileTree: true # for rendering changes files in a tree format
  showListFooter: false # for seeing the '5 of 20' message in list panels
  showRandomTip: false
  showBottomLine: false # for hiding the bottom information line (unless it has important information to tell you)
  showCommandLog: true
  showIcons: false

disableStartupPopups: true
notARepository: 'skip' # one of: 'prompt' | 'create' | 'skip'
os:
  editPreset: 'nvim'
