gui:
  theme: # https://github.com/catppuccin/lazygit/blob/main/themes/frappe.yml
    lightTheme: false 
    activeBorderColor:
      - "#a6d189" # Green
      - bold
    inactiveBorderColor:
      - "#c6d0f5" # Text
    optionsTextColor:
      - "#8caaee" # Blue
    selectedLineBgColor:
      - "#414559" # Surface0
    selectedRangeBgColor:
      - "#414559" # Surface0
    cherryPickedCommitBgColor:
      - "#81c8be" # Teal
    cherryPickedCommitFgColor:
      - "#8caaee" # Blue
    unstagedChangesColor:
      - red       # Red

  showFileTree: true # for rendering changes files in a tree format
  showListFooter: false # for seeing the '5 of 20' message in list panels
  showRandomTip: false
  showBottomLine: false # for hiding the bottom information line (unless it has important information to tell you)
  showCommandLog: true
  showIcons: false

disableStartupPopups: true
notARepository: 'skip' # one of: 'prompt' | 'create' | 'skip'
os:
  editCommand: 'nvim' 
