cmap ;cac /home/oh/.cache
cmap ;cf /home/oh/.config
cmap ;D /home/oh/Downloads
cmap ;d /home/oh/Documents
cmap ;dt /home/oh/.local/share
cmap ;rr /home/oh/.local/src
cmap ;h /home/oh
cmap ;m /home/oh/Music
cmap ;mn /mnt
cmap ;pp /home/oh/Pictures
cmap ;sc /home/oh/.local/bin
cmap ;src /home/oh/.local/src
cmap ;vv /home/oh/Videos
cmap ;bf /home/oh/.config/shell/bm-files
cmap ;bd /home/oh/.config/shell/bm-dirs
cmap ;cfx /home/oh/.config/x11/xresources
cmap ;cfb ~/.local/src/dwmblocks/config.h
cmap ;cfv /home/oh/.config/nvim/init.vim
cmap ;cfz /home/oh/.config/zsh/.zshrc
cmap ;cfa /home/oh/.config/shell/aliasrc
cmap ;cfp /home/oh/.config/shell/profile
cmap ;cfm /home/oh/.config/mutt/muttrc
cmap ;cfn /home/oh/.config/newsboat/config
cmap ;cfu /home/oh/.config/newsboat/urls
cmap ;cfmb /home/oh/.config/ncmpcpp/bindings
cmap ;cfmc /home/oh/.config/ncmpcpp/config
cmap ;cfl /home/oh/.config/lf/lfrc
cmap ;cfL /home/oh/.config/lf/scope
cmap ;cfX /home/oh/.config/sxiv/exec/key-handler
