# Sets user-defined palette
palette = "catppuccin_frappe"

# Inserts a blank line between shell prompts
add_newline = false

# One-line prompt
# [line_break]
# disabled = false

# format = '''
# [┌─── ](bold green)$directory$rust$package
# [└─🞔 ](bold green) '''

# format = """
# [░▒▓](#89b4fa)\
# [  ](bg:#89b4fa fg:#1e1e2e)\
# [](bg:#b4befe fg:#89b4fa)\
# $directory\
# [](fg:#b4befe bg:#313244)\
# $git_branch\
# $git_status\
# [](fg:#313244)\
# \n$character
# """

# [➜ ](green)\
# [|-🞔 ](red)\
# [󰄛 ](red)\

format = """
[➜ ](green)\
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$jobs\
${env_var.yazi_level}\
$character\
"""

# [|-🞔  ](bold mauve)

[character]
# https://symbl.cc/en/276D/
# success_symbol = "[❭](green)"
# error_symbol = "[❭](red)"
# vimcmd_symbol = "[❬](orange)"

# success_symbol = "[❯](green)"
# error_symbol = "[❯](red)"
# vimcmd_symbol = "[❮](green)"

# success_symbol = "[❯](green)"
# error_symbol = "[❯](red)"
# vimcmd_symbol = "[❮](green)"
# success_symbol = "[-|](green)"
# error_symbol = "[✕](red)"
# error_symbol = "[✘](red)"

# success_symbol = "[🞔 ](green)"
# error_symbol = "[🞔 ](red)"
# vimcmd_symbol = "[🞕 ](orange)"
disabled = false

[username]
format = '[$user]($style)@'
style_user = 'green'
# show_always = true

[hostname]
ssh_symbol = ''
trim_at = ''
format = '[$ssh_symbol$hostname]($style): '
style = 'green'
# ssh_only = false

[directory]
truncation_length = 1
read_only = " "
style = "bold sapphire"
# style = "bold blue"

[git_branch]
format = "[git:$branch]($style)"
style = "overlay0"
symbol = " "

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "overlay0"

[git_status]
# format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](218) ($ahead_behind$stashed )]($style)"
format = "[[(*$conflicted$untracked$modified$staged$renamed$deleted)](overlay0) ($ahead_behind$stashed )]($style)"
style = "cyan"
conflicted = "​"
untracked = "​"
modified = "​"
staged = "​"
renamed = "​"
deleted = "​"
stashed = "≡"

# https://github.com/fitrh/dotfiles/blob/main/.config/starship/starship.toml
#
# ahead = '[﯁ ](bright-blue)[$count](bright-white bold) '
# behind = '[﮾ ](white)[$count](bright-white bold) '
# diverged = '[ ](purple)|[ ﯁ ](bright-blue)[$ahead_count](bright-white bold)[ ﮾ ](white)[$behind_count](bright-white) '


[jobs]
# symbol = ''
symbol = '✦ '
style = 'red'

[cmd_duration]
format = "[$duration]($style) "
style = "yellow"

# palette tables should be last in the config
[palettes.catppuccin_frappe]
rosewater = "#f2d5cf"
flamingo = "#eebebe"
pink = "#f4b8e4"
mauve = "#ca9ee6"
red = "#e78284"
maroon = "#ea999c"
peach = "#ef9f76"
yellow = "#e5c890"
green = "#a6d189"
teal = "#81c8be"
sky = "#99d1db"
sapphire = "#85c1dc"
blue = "#8caaee"
lavender = "#babbf1"
text = "#c6d0f5"
subtext1 = "#b5bfe2"
subtext0 = "#a5adce"
overlay2 = "#949cbb"
overlay1 = "#838ba7"
overlay0 = "#737994"
surface2 = "#626880"
surface1 = "#51576d"
surface0 = "#414559"
base = "#303446"
mantle = "#292c3c"
crust = "#232634"
#

# https://github.com/Sonico98/yazi-prompt.sh?tab=readme-ov-file
[env_var.yazi_level]
description = "Indicate the shell was launched by `yazi`"
variable = "YAZI_LEVEL"
# 🦆: U+1f986 Duck
# Alternatively: " ": U+E795 <Private Use>
symbol = "🦆"
format = '[$symbol]($style)'
