#!/bin/sh

# Autoload zsh vcs_info function (-U autoload w/o substition, -z use zsh style)
autoload -Uz vcs_info
## autoload colors
autoload -U colors && colors

# enable only git 
zstyle ':vcs_info:*' enable git 

# setup a hook that runs before every ptompt. 
precmd_vcs_info() { vcs_info }
precmd_functions+=( precmd_vcs_info )

# Enable substitution in the prompt.
setopt prompt_subst

# add a function to check for untracked files in the directory.
# from https://github.com/zsh-users/zsh/blob/master/Misc/vcs_info-examples
# Make sure you have added staged to your 'formats':  %c
zstyle ':vcs_info:git*+set-message:*' hooks git-untracked
# 
+vi-git-untracked(){
    if [[ $(git rev-parse --is-inside-work-tree 2> /dev/null) == 'true' ]] && \
        git status --porcelain | grep '??' &> /dev/null ; then
        # This will show the marker if there are any untracked files in repo.
        # If instead you want to show the marker only if there are untracked
        # files in $PWD, use:
        #[[ -n $(git ls-files --others --exclude-standard) ]] ; then
        hook_com[staged]+='?' # signify new files with a ?
    fi
}

# Enable checking for (un)staged changes, enabling use of %u and %c
zstyle ':vcs_info:*' check-for-changes true

# TODO: https://gist.github.com/chrisnolet/d3582cd63eb3d7b4fcb4d5975fd91d04

# TODO: Added to the prompt as ${p_host}
# if [[ -n "$SSH_CLIENT"  ||  -n "$SSH2_CLIENT" ]]; then 
#     p_host='%F{yellow}%M%f'
#   else
#     p_host='%F{green}%M%f'
# fi

# Here is how staged/unstaged marks works out of the box:
#   unstaged: you have changes that you have not staged (added) to your git repo
#   staged: you have changes that you staged (added) to your current git repo, but you have not created a commit yet
#
# Set custom strings for an unstaged vcs repo changes (*) and staged changes (+)
zstyle ':vcs_info:*' stagedstr ' +'    # '%F{green}●'
zstyle ':vcs_info:*' unstagedstr '*'  # '%F{yellow}●'

zstyle ':vcs_info:git:*' actionformats '(%b|%a%u%c)'
zstyle ':vcs_info:git:*' formats " %{$fg[blue]%}git:(%{$fg[blue]%}%b%{$fg[blue]%}%{$fg[yellow]%}%u%c%m%{$fg[blue]%})%{$reset_color%}"

  # https://unicode-table.com/en/1F794/
  # U+1F794 = 🞔  (Name: White Square Containing Black Very Small Square; Block: Geometric Shapes Extended)

# PROMPT="%B%{$fg[blue]%}[%{$fg[white]%}%n%{$fg[red]%}@%{$fg[white]%}%m%{$fg[blue]%}] %(?:%{$fg_bold[green]%} :%{$fg_bold[red]%} )%{$fg[cyan]%}%c%{$reset_color%}"
PROMPT="%B%(!:%{$fg[red]%}🞕  :%{$fg[green]%}🞔  )%{$fg[cyan]%}%c%{$reset_color%}"
# PROMPT="%B%(!:%{$fg[red]%}🞕  :%{$fg[green]%}  )%{$fg[cyan]%}%c%{$reset_color%}"
PROMPT+="\$vcs_info_msg_0_ "

# TODO: How to configure PS2 prompt?
# PS2=$'%_>'

# TODO:  look into this for more colors
# https://stevelosh.com/blog/2010/02/my-extravagant-zsh-prompt/  
