return {
  inlayHint = true, -- don't enbale by default
  keymenu = {
    mini_clue = false,
  },
  pde = {
    ai = true,
    angular = false,
    cpp = false,
    csharp = false,
    docker = false,
    elixir = false,
    flutter = false,
    go = false,
    html = true,
    java = false,
    json = true,
    julia = false,
    jupyter = false,
    lua = true,
    python = false,
    r = false,
    react = true,
    ruby = false,
    rust = false,
    solidity = false,
    svelte = false,
    tailwind = false,
    terraform = false,
    typescript = true,
    vuejs = false,
    yaml = true,
  },
}
