#!/bin/sh
# Set brightness via xbrightness when gammastep/redshift status changes

# Set brightness values for each status.
# Range from 1 to 100 is valid
brightness_day=85
brightness_transition=50
brightness_night=30
#
# Set fps for smoooooth transition
fps=1000
#
# Adjust this grep to filter only the backlights you want to adjust
backlights=($(xbacklight -list | grep ddcci*))

# set_brightness() {
# 	for backlight in "${backlights[@]}"
# 	do
#     # Only works for X11
# 		# xbacklight -set $1 -fps $fps -ctrl $backlight &
#     # Works for Wayland and X11
#     ddcutil --bus 10 setvcp 10 "$1"
#     notify-send "Brightness" "Brightness changed to $1"
# 	done
# }

# Run 'ddcutil detect' to find monitor I2C bus number.
# For example: I2C bus:  /dev/i2c-10
BUSES="10 11"

set_brightness() {
    brightness="$1"

    for bus in $BUSES; do
        ddcutil --bus "$bus" setvcp 10 "$brightness" &
    done

    wait

    notify-send "Brightness" "Brightness changed to $brightness"
}

if [ "$1" = period-changed ]; then
	case $3 in
		night)
			set_brightness $brightness_night
			;;
		transition)
			set_brightness $brightness_transition
			;;
		daytime)
			set_brightness $brightness_day
			;;
	esac
fi
