[general]
color = "blue"
interval = 250
blink = true
bold = true

[position]
horizontal = "center"
vertical = "center"

[date]
fmt = "%d-%m-%Y"
# fmt = "%A, %B %d, %Y"
use_12h = false
utc = false
hide_seconds = true
