#!/usr/bin/env bash

# Shell Options
stty -ixon # Disable Ctrl+S and Ctrl+Q

shopt -s autocd         # Allows you to cd into directory merely by typing the directory name
shopt -s expand_aliases # expand aliases

shopt -s cdspell # autocorrects typos (eg: cd /ect becomes cd /etc)
shopt -s extglob

# Sometimes you have multiple terminal windows open at the same time. By default,
# the window that closes last, will overwrite the bash history file, loosing the
# history of all the other terminal windows and ssh sessions in the process.
# This can be avoided by this little setting:
shopt -s histappend # merge session histories

# Bash Version >= 4
shopt -s autocd 2>/dev/null || true
shopt -s dirspell 2>/dev/null || true

# Default programs
export EDITOR="nvim" # $EDITOR use nvim in terminal
export VISUAL="nvim" # $VISUAL use nvim in GUI mode
export TERMINAL="kitty"
export BROWSER="librewolf"

# Use nvim as manpager `:h Man`
export MANPAGER='nvim +Man!'
export MANWIDTH=999

# less/man colors
export PAGER="less"
# Alternative pagers:
#   - https://github.com/walles/moar
#     export PAGER="moar"
#   - https://github.com/lucc/nvimpager
#     export PAGER="nvimpager"
#   - https://github.com/I60R/page
#     export PAGER="page -q 90000 -z 90000"

# export LESSHISTFILE="-" # Disable less history.
# export LESSHISTFILE="$XDG_CACHE_HOME/less_history"
export LESS=-R
# Man page bold
export LESS_TERMCAP_mb="$(printf '%b' '[1;31m')" # begin bold
export LESS_TERMCAP_md="$(printf '%b' '[1;36m')" # begin blink
export LESS_TERMCAP_me="$(printf '%b' '[0m')"    # reset bold/blink
# Status bar and search hits
export LESS_TERMCAP_so="$(printf '%b' '[01;44;33m')" # begin reverse video
export LESS_TERMCAP_se="$(printf '%b' '[0m')"        # reset reverse video
# Man page underline
export LESS_TERMCAP_us="$(printf '%b' '[1;32m')" # begin underline
export LESS_TERMCAP_ue="$(printf '%b' '[0m')"    # reset underline

# fzf
# Details:
#   - https://thevaluable.dev/fzf-shell-integration/
#   - https://thevaluable.dev/practical-guide-fzf-example/

# NOTE: fzf will use this default command if and only if you don’t give any input.

# Use the CLI find (default) to get all files, excluding any filepath
# containing the string "git".
# export FZF_DEFAULT_COMMAND='find . -type f ! -path "*git*"'

# Use the CLI fd to respect ignore files (like '.gitignore'),
# display hidden files, and exclude the '.git' directory.
# export FZF_DEFAULT_COMMAND='fd . --hidden --exclude ".git"'

# Use the CLI ripgrep to respect ignore files (like '.gitignore'),
# display hidden files, and exclude the '.git' directory.
export FZF_DEFAULT_COMMAND='rg --files --hidden --glob "!.git"'

export FZF_CTRL_T_COMMAND="$FZF_DEFAULT_COMMAND"

export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -n 10'"

# export FZF_DEFAULT_OPTS="--layout=reverse --border --height 40%"

# FZF_COLORS="bg+:-1,\
# fg:gray,\
# fg+:white,\
# border:black,\
# spinner:0,\
# hl:yellow,\
# header:blue,\
# info:green,\
# pointer:red,\
# marker:blue,\
# prompt:gray,\
# hl+:red"

# Frappe https://github.com/catppuccin/fzf
# FZF_COLORS="bg+:#414559,\
# bg:#303446,\
# spinner:#f2d5cf,\
# hl:#e78284,\
# fg:#c6d0f5,\
# header:#e78284,\
# info:#ca9ee6,\
# pointer:#f2d5cf,\
# marker:#f2d5cf,\
# fg+:#c6d0f5,\
# prompt:#ca9ee6,\
# hl+:#e78284"

# Color configuration
# https://github.com/junegunn/fzf/wiki/Color-schemes#color-configuration
#
# fg          Text
# bg          Background
# preview-fg  Preview window text
# preview-bg  Preview window background
# hl          Highlighted substrings
# fg+         Text (current line)
# bg+         Background (current line)
# gutter      Gutter on the left (defaults to bg+)
# hl+         Highlighted substrings (current line)
# info        Info
# border      Border of the preview window and horizontal separators (--border)
# prompt      Prompt
# pointer     Pointer to the current line
# marker      Multi-select marker
# spinner     Streaming input indicator
# header      Header
FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
--color=bg+:#414559,bg:#303446,spinner:#F2D5CF,hl:#E78284 \
--color=fg:#C6D0F5,header:#E78284,info:#CA9EE6,pointer:#F2D5CF \
--color=marker:#BABBF1,fg+:#C6D0F5,prompt:#CA9EE6,hl+:#E78284 \
--color=selected-bg:#51576D \
--color=border:#737994,label:#C6D0F5"

export FZF_DEFAULT_OPTS="$FZF_DEFAULT_OPTS \
--height 60% \
--border rounded \
--prompt=' ' \
--pointer   \
--layout reverse "

# --color '$FZF_COLORS' \
# --prompt='> ' \
#   --pointer ▍ \
#   --marker ⇒"
# --pointer ▶ \
# --prompt '∷ ' \
# --pointer='→' \
# --marker='♡' \

# Old config
# export FZF_DEFAULT_OPTS=$FZF_DEFAULT_OPTS"
# --color=bg+:#414559,bg:#303446,spinner:#f2d5cf,hl:#e78284
# --color=fg:#c6d0f5,header:#e78284,info:#ca9ee6,pointer:#f2d5cf
# --color=marker:#f2d5cf,fg+:#c6d0f5,prompt:#ca9ee6,hl+:#e78284"

# FZF Auto-completion
# ---------------
source "/usr/share/fzf/completion.bash" 2>/dev/null

# FZF Key bindings
# ------------
source "/usr/share/fzf/key-bindings.bash"

# Load external files
[ -f "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliases" ] && source "${XDG_CONFIG_HOME:-$HOME/.config}/shell/aliases"
